services:
  traefik:
    image: traefik:v2.11
    container_name: sandbox-traefik
    command:
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:8001
      - --entrypoints.websecure.address=:8443
      - --tls.certificates.certFile=/etc/letsencrypt/live/traefik.rfess.fr/fullchain.pem
      - --tls.certificates.keyFile=/etc/letsencrypt/live/traefik.rfess.fr/privkey.pem
    ports:
      - "8001:8001"
      - "8443:8443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - sandbox-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.rfess.fr`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.service=api@internal"

networks:
  sandbox-network:
    external: true
