services:
  traefik:
    image: traefik:v2.11
    container_name: sandbox-treafik
    command:
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-test
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`sandbox.traefik.me`)"
      - "traefik.http.routers.traefik.service=api@internal"

networks:
  proxy-test:
    external: true
