services:
  traefik:
    image: ${TRAEFIK_IMAGE}
    container_name: ${TRAEFIK_CONTAINER_NAME}
    command:
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:${TRAEFIK_HTTP_PORT}
      - --entrypoints.websecure.address=:8443
    ports:
      - "${TRAEFIK_HTTP_PORT}:${TRAEFIK_HTTP_PORT}"
      - "${TRAEFIK_DASHBOARD_PORT}:${TRAEFIK_DASHBOARD_PORT}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - sandbox-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.rfess.fr`)"
      - "traefik.http.routers.traefik.service=api@internal"

networks:
  sandbox-network:
    external: true
